Form section
baezluise/Portfolio pull request #3
Opened 2023-01-24 17:13 UTC by baezluise

Form structure created and styled.

- Colors and borders added.
- Fonts added.
- Button actions added.

2023-01-24 23:16 UTC, baezluise commented
-Centered the form.
-Added form image.
-Linked formspree.
-Deleted error in about me.

2023-01-24 23:28 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @baezluise, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 23:28 UTC, brainconnect93 commented on index.html
> +        <li class="para-form">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</li>
- [ ] I would kindly suggest you work on the form action address by creating a form-spree account and generating an `id` to use in the form action in such a way that if a visitor sends a message to you from your portfolio it submits the form and you automatically receive the message in your mail. But currently, I could not reach out to you via the form-spree. Any time I tried to send a message it throw an error. Kindly follow this [link](https://formspree.io/html) for more understanding.

Error Message 👇 

![hashid](https://user-images.githubusercontent.com/78634841/214443784-3594af56-7f9a-4be4-8f82-67354c20997a.png)

2023-01-25 04:42 UTC, baezluise commented
Required changes made.

2023-01-25 04:52 UTC, Shedrack-Sunday approved these changes
Hi @baezluise     👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
- Linters are passing 
- Form submits successfully 

 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._
 

 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 04:54 UTC, merged